---
title: "Lab2.1"
author: "marininvp"
date: "2023-04-09"
output: html_document
---
## Подключение библиотек

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(arrow)
library(dplyr)
library(stringr)
```

## Загрузка данных 

```{r}
new_data <- arrow::read_csv_arrow("D:\\ProjectsRstudio\\2_sem_R\\LAB1\\gowiththeflow_20190826.csv",schema=schema(timestamp=int64(),src=utf8(),dst=utf8(),port=int32(),bytes=int32()))
```
## Отображение первых 10-ти записей размеченной таблицы
```{r}
head(new_data,10)
```
## Фильтрация данных по условию задачи
```{r}
filter(new_data,str_detect(src,"^((12|13|14)\\.)"),str_detect(dst,"^((12|13|14)\\.)",negate=TRUE)) %>% select(src,bytes) %>% group_by(src)%>% summarise(bytes=sum(bytes))%>% slice_max(bytes)%>% select(src)
```

## Топ 10 самых активных ip-адресов
```{r}
new_data %>% select(src,dst,bytes) %>% filter(str_detect(src,"^((12|13|14)\\.)"),str_detect(dst,"^((12|13|14)\\.)",negate=TRUE)) %>%
group_by(src) %>% summarise(loads = sum(bytes)) %>% arrange(desc(loads)) %>% head(10)
```

